# Generated by Django 3.2.7 on 2021-09-27 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100, unique=True, verbose_name='Адрес доставки')),
                ('coordinates', models.JSONField(verbose_name='Координаты')),
                ('metro', models.TextField(blank=True, null=True, verbose_name='Станция метро')),
                ('district', models.TextField(blank=True, null=True, verbose_name='Район')),
                ('fetched_from_api_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
    ]
