# Generated by Django 3.2.7 on 2021-09-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_to_swap',
            field=models.ManyToManyField(related_name='_items_item_item_to_swap_+', to='items.Item'),
        ),
    ]
