# Generated by Django 3.2.7 on 2021-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_item_to_swap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_to_swap',
        ),
        migrations.AddField(
            model_name='item',
            name='items_to_swap',
            field=models.ManyToManyField(related_name='_items_item_items_to_swap_+', to='items.Item'),
        ),
    ]
