# Generated by Django 3.2.7 on 2021-09-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210925_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_to_swap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_to_swap_offers', to='items.item', verbose_name='вещь, предлагаемая на обмен')),
                ('wanted_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_offers', to='items.item', verbose_name='желаемая вещь')),
            ],
        ),
    ]
