# Generated by Django 3.2.7 on 2021-09-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items_to_swap',
        ),
    ]
