# Generated by Django 3.2.7 on 2021-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_item_items_to_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_accept',
            field=models.NullBooleanField(default=None),
        ),
    ]
