# Generated by Django 3.2.7 on 2021-09-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_offer_is_accept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_accept',
            new_name='is_accepted',
        ),
    ]
