# Generated by Django 3.2.7 on 2021-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_offer_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
